#!/bin/bash
#===============================================================================
# Title:       importToAgent.sh
#
# Disclaimer:  This script is provided "AS IS" and without any official support
#              from Oracle. Its use needs to be performed using details from the
#              comments section and/or readme file (if one is included). Any bugs
#              encountered, feedback, and/or enhancement requests are welcome.
#
#              No liability for the contents of this script can be accepted. Use
#              the concepts, examples, and information at your own risk. However,
#              great care has been taken to ensure that all technical information
#              is accurate and as useful as possible.
#
#              Copyright © 2018, Oracle and/or its affiliates. All rights reserved.
#              The Universal Permissive License (UPL), Version 1.0
#
#
# Description: This script is used to validate and kick off the WebLogic WLST
#              importToAgent.py script.  It relies on the importToAgentEnv.sh
#              and will check for the following:
#                1. Is the Connectivity Agent running
#                2. Check for importToAgent.ini (generated by createKeystore.sh)
#                3. Check for WLST script in $AGENT_HOME/oracle_common/common/bin
#
#              If no command-line arguments are provided, the following defaults
#              will be used:
#                * Agent Server User:          weblogic
#                * Agent Server User Password: welcome1
#                * Agent Server Host Name:     localhost
#                * Agent Server Host Port:     7001
#
# Author:      Greg Mally
#
# Date:        18-May-2018
#
# Version:     1.1
#
# Usage:       ./importToAgent.sh -au=agentAdmin -ap=admin! -ah=agent.demo.org -aport=7101
#
# Notes:       The above usage assumes that this script has execute permission.
#              If it doesn't have execute permission, then add "bash" in front
#              of the command.  For example, bash ./importToAgent.sh ...
#
#              After this script validates the command-line arguments and the
#              various points in the description above, it will kick off WLST
#              with the importToAgent.py and provide the agent user name,
#              password, host name, and host port.
#
#              After running this script it is recommended to bounce the
#              Connectivity Agent server to make sure everything loads as
#              expected.
#
# History:     1.0 - Initial release on 31-October-2016
#
#              1.1 - Added function for inputting the agent password in a
#                    masked text fashion.
#
#                    Removed the -ap/--agentpassword option
#
#===============================================================================

. ./importToAgentEnv.sh

##################################################
# Default values
##################################################
AGENTUSER=weblogic
AGENTPASSWORD=welcome1
AGENTHOST=localhost
AGENTPORT=7001


##################################################
# Function: Read secret string
# Version 1.1 - Added this function
##################################################
function read_secret {
    # Disable echo
    stty -echo
    
    # Set up trap to ensure echo is enabled before exiting if the script
    # is terminated while echo is disabled.
    trap 'stty echo' EXIT
    
    # Read secret
    read SECRET
    
    # Enable echo and remove trap
    stty echo
    trap - EXIT
    
    # echo the secret to be captured in a bash variable
    echo $SECRET
}


##################################################
# Process arguments
# Version 1.1 - Remove agent password
##################################################
for i in "$@"
do
case $i in
    -au=*|--agentuser=*)
    AGENTUSER="${i#*=}"
    shift
    ;;
    -ah=*|--agenthost=*)
    AGENTHOST="${i#*=}"
    shift
    ;;
    -aport=*|--agentport=*)
    AGENTPORT="${i#*=}"
    shift
    ;;
    --help)
    HELP=YES
    ;;
    *)
    # unknown option
    ;;
esac
done


##################################################
# Check for usage
# Version 1.1 - Remove agent password
##################################################
if [[ ( -z $AGENTUSER ) || ( -z $AGENTHOST ) || ( -z $AGENTPORT ) || ( "$HELP" = "YES" ) ]]; then
    echo "Usage:       ./$0 [-au=AgentUsername] [-ah=AgentServerHost] [-aport=AgentServerPort]"
    echo "Defaults:    ./$0 -au=$AGENTUSER -ap=$AGENTPASSWORD -ah=$AGENTHOST -aport=$AGENTPORT"
    echo "For example, ./$0 -au=agentAdmin -ap=admin! -ah=agent.demo.org -aport=7101"
    exit 1
fi


##################################################
# Setup Variables
##################################################
export AGENT_HTTP_URL=http://$AGENTHOST:$AGENTPORT
export WLST=$AGENT_HOME/oracle_common/common/bin/wlst.sh


#################################################
# Check for Connectivity Agent Running
##################################################
wget -q $AGENT_HTTP_URL/console -O /dev/null

if [[ $? -ne 0 ]]; then
    echo "Agent is not running at: $AGENT_HTTP_URL"
    echo "Please start the Agent and try again."
    exit 1
fi


##################################################
# Check for importToAgent.ini that is generated
# by the createKeystore.sh script
##################################################
if [[ ! -f importToAgent.ini ]]; then
   echo "WLST .ini not found: importToAgent.ini"
   echo "Please generate using createKeystore.sh"
   exit 1
fi


##################################################
# Check for wlst
##################################################
if [[ ! -f $WLST ]]; then
   echo "WLST not found: $WLST"
   echo "Please verify Agent home: $AGENT_HOME"
   echo "The AGENT_HOME can be found in the importToAgentEnv.sh"
   exit 1
fi


##################################################
# Get Agent password
# Version 1.1 - Added agent password read
##################################################
# Display prompt, get password, and echo newline
printf "Agent Password: "
AGENTPASSWORD="$(read_secret)"
echo


##################################################
# Start the import process
##################################################
$WLST ./importToAgent.py -u $AGENTUSER -p $AGENTPASSWORD -h $AGENTHOST -t $AGENTPORT
